### ISSUE TITLE
Homepage does not display posts

### ISSUE THREAD

**Issue by onedrawingperday** [ThemeTony/hugo-theme-tony#3]
@FFRaycoder 

My patience is beginning to run out.

Your theme has been approved for a week. 

Then you update it and the theme is broken twice due to multiple errors described in #1 and #2 

Now in the latest version you have removed the posts list and instead point users to an external demo.

That is not how things work I am afraid.

***
**EDIT**
The theme has been added to the `noDemo` array of the Hugo Themes Build Script in https://github.com/gohugoio/hugoThemes/commit/6c6953894b0308e95620ba2937bc6224b0a01faa 

We do not accept demos that point to external pages for their content.

You have 30 calendar days to restore the demo content on list pages as it was when the theme was approved.

After this time frame the theme will be removed.
***
cc: @digitalcraftsman

**Comment by FFRaycoder** [comment]
I don't understand what you mean. It displays very well on my device.
![image](https://user-images.githubusercontent.com/58381667/82721793-4bbec180-9cf3-11ea-953b-e04d8e8ac956.png)
You mean [that](https://github.com/ThemeTony/hugo-theme-tony/blob/master/exampleSite/config.toml#L27-L39)?

**Comment by FFRaycoder** [comment]
Hi, I really want to find the cause of the problem. Look [here](https://github.com/ThemeTony/hugo-theme-tony/commit/4197966a3eb16a15ed391043e215fded8f3cceea#L145)

**Comment by onedrawingperday** [comment]
@FFRaycoder 

As stated in the Hugo Themes [README](https://github.com/gohugoio/hugoThemes#adding-a-theme-to-the-list)

> You need to test your theme's demo with the content directory from the Hugo Basic Example repository.

The demo content is inherited from the [Hugo Basic Example](https://github.com/gohugoio/hugoBasicExample/tree/master/content) repository.

Your recent commits adding the `mainSections` parameter in the `exampleSite/config.toml` broke the theme demo because the Hugo Basic Example has a `post` section and not a `posts` section.

As stated in the [documentation](https://gohugo.io/functions/where/#mainsections)

> To list the most relevant pages on the front page or similar, you should use the site.Params.mainSections list instead of comparing section names to hard-coded values like "posts" or "post"

You really should not have added the `mainSections` parameter. 

So do remove it and then let me know.

Also please try being more careful with your theme's updates.
Test them before pushing them to master.

**Comment by onedrawingperday** [comment]
Also change the URL of [this parameter](https://github.com/ThemeTony/hugo-theme-tony/blob/master/exampleSite/config.toml#L69) so that it does not point to the external demo, make it point to the homepage of your hosted Hugo Themes demo like so: `"/"`

We really do not allow linking to external pages from demos hosted on Hugo Themes.

That is also important and again notify me once you do it.

**Comment by FFRaycoder** [comment]
Okay, it has been fixed. I will pay attention to every subsequent submission.

**Comment by FFRaycoder** [comment]
fixed.

**Comment by onedrawingperday** [comment]
@FFRaycoder 

I am afraid that the issue is not fixed. 
You did not do what I asked you. 

Above I asked you to remove the `mainSections` parameter.
However you did not remove, instead you deleted the `posts` word and [left it as an empty array](https://github.com/ThemeTony/hugo-theme-tony/blob/master/exampleSite/config.toml#L151).

Also it appears that you made changes to theme and you again did not update the theme's resources.

You always have to regenerate and re-commit the theme's resources whenever you make changes.

So do delete line 151 of `config.toml` and fix the resources.

**Comment by FFRaycoder** [comment]
ok...

**Comment by FFRaycoder** [comment]
Maybe something went wrong with my automatic deployment script.

**Comment by FFRaycoder** [comment]
I don't agree with you very much. The Tony theme has a blog post of type `status`, which will only appear on the homepage. If mainSection is removed, it will not be displayed.
If I am not correct, please correct me.

**Comment by onedrawingperday** [comment]
@FFRaycoder 

This is getting nowhere. Above I gave you detailed and qualified advice about fixing the theme demo. There is nothing to agree with. You either follow the advice to the letter and fix your theme or leave it as is.

The [Doc](https://gohugo.io/functions/where/#mainsections) is quite explanatory. `mainSections` is an internal Hugo method. Hugo detects which section has the most pages. Right now you have set it to nothing and as such nothing displays on the homepage.

Also [we offer detailed instructions](https://github.com/gohugoio/hugoThemes#testing-a-theme-with-the-hugo-themes-website-build-script) in the README of the Hugo Themes repo for testing a theme with the Hugo Themes Build Script.

My time offering support for your theme has run out. 

You theme is still in the noDemo array and the original notice in the first post still stands. In 28 days I will revisit the Tony theme and if the homepage is still empty or the demo does not generate then the theme will be removed.

**Comment by FFRaycoder** [comment]
ok, fixed now.
